# Perform other matrix operations like converting matrix data to absolute values, taking the negative of matrix values, additing/removing rows/columns from a matrix, finding the maximum or minimum values in a matrix or in a row/column, and finding the sum of some/all elements in a matrix.

In [9]:
import numpy as np

c=np.array([[1,2,4],[5,6,8]])
print("MATRIX:\n", c, '\n')

v=np.sin(c)
print("SINE MATRIX:\n", v,'\n')
print("ABSOLUTE MATRIX:\n", np.abs(v),'\n')

d=np.append(c,np.array([[9,10,12]]), axis=0)
print("APPENDED MATRIX:\n", d,'\n')

print("2nd ROW DELETED:\n", np.delete(d,1,0),'\n')
print("2nd COLUMN DELETED:\n", np.delete(d,1,1),'\n')

print("MAX. ELEMENT OF THE MATRIX:", np.max(d),'\n')
print("MAX. ELEMENT OF THE MATRIX:", np.min(d),'\n')

print("SUM OF ALL THE ELEMENTS OF THE MATRIX:",np.sum(d),'\n')
print("COLUMN-WISE SUM OF ELEMENTS\n", np.sum(d,axis=0))

MATRIX:
 [[1 2 4]
 [5 6 8]] 

SINE MATRIX:
 [[ 0.84147098  0.90929743 -0.7568025 ]
 [-0.95892427 -0.2794155   0.98935825]] 

ABSOLUTE MATRIX:
 [[0.84147098 0.90929743 0.7568025 ]
 [0.95892427 0.2794155  0.98935825]] 

APPENDED MATRIX:
 [[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]] 

2nd ROW DELETED:
 [[ 1  2  4]
 [ 9 10 12]] 

2nd COLUMN DELETED:
 [[ 1  4]
 [ 5  8]
 [ 9 12]] 

MAX. ELEMENT OF THE MATRIX: 12 

MAX. ELEMENT OF THE MATRIX: 1 

SUM OF ALL THE ELEMENTS OF THE MATRIX: 57 

COLUMN-WISE SUM OF ELEMENTS
 [15 18 24]
