# Perform vectorized implementation of simple matrix operation like finding the transpose of a matrix, adding, subtracting or multiplying two matrices.

In [15]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[1,1,1]])
b=np.array([[6,7,8],[9,10,11],[2,2,2]])
print("MATRIX 1:\n", a,'\n')
print("MATRIX 2:\n", b,'\n')
print("TRANSPOSE OF MATRIX 1:\n", np.transpose(a),'\n')
print("M1+M2:\n", a+b,'\n')
print("M1-M2:\n", b-a,'\n')
print("M1*M2:\n", np.matmul(a,b),'\n')

MATRIX 1:
 [[1 2 3]
 [4 5 6]
 [1 1 1]] 

MATRIX 2:
 [[ 6  7  8]
 [ 9 10 11]
 [ 2  2  2]] 

TRANSPOSE OF MATRIX 1:
 [[1 4 1]
 [2 5 1]
 [3 6 1]] 

M1+M2:
 [[ 7  9 11]
 [13 15 17]
 [ 3  3  3]] 

M1-M2:
 [[5 5 5]
 [5 5 5]
 [1 1 1]] 

M1*M2:
 [[30 33 36]
 [81 90 99]
 [17 19 21]] 

