# Perform basic operations on matrices (like addition, subtraction, multiplication) and display specific rows or columns of the matrix.

In [7]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[7,8,9]])

s=a+b
print("Matrix after ADDITION:\n", s,'\n')
print("3rd Column of Sum Matrix:\n", s[:,2],'\n')

d=b-a
print("Matrix after SUBTRACTION:\n", d,'\n')
print("2nd Row of Difference Matrix:\n", d[1,:],'\n')

m=a*b
print("Matrix after MULTIPLICATION:\n", m,'\n')
print("M[1,2]: ", m[1,2],'\n')

Matrix after ADDITION:
 [[ 5  7  9]
 [11 13 15]] 

3rd Column of Sum Matrix:
 [ 9 15] 

Matrix after SUBTRACTION:
 [[3 3 3]
 [3 3 3]] 

2nd Row of Difference Matrix:
 [3 3 3] 

Matrix after MULTIPLICATION:
 [[ 4 10 18]
 [28 40 54]] 

M[1,2]:  54 

