In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

adv = pd.read_csv("Advertising.csv")
print(adv.head())

x1=adv['TV']
x2=adv['radio']
x3=adv['newspaper']
y=adv['sales']

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9


In [6]:
x1=np.array(x1)
x2=np.array(x2)
x3=np.array(x3)
y=np.array(y)

n=len(x1)

x_bias=np.ones((n,1))
x1_n=np.reshape(x1,(n,1))
x2_n=np.reshape(x2,(n,1))
x3_n=np.reshape(x3,(n,1))

x=np.append(x_bias,x1_n,axis=1)
x=np.append(x,x2_n,axis=1)
x=np.append(x,x3_n,axis=1)
print('X= \n',x)

X= 
 [[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]
 [  1.    8.7  48.9  75. ]
 [  1.   57.5  32.8  23.5]
 [  1.  120.2  19.6  11.6]
 [  1.    8.6   2.1   1. ]
 [  1.  199.8   2.6  21.2]
 [  1.   66.1   5.8  24.2]
 [  1.  214.7  24.    4. ]
 [  1.   23.8  35.1  65.9]
 [  1.   97.5   7.6   7.2]
 [  1.  204.1  32.9  46. ]
 [  1.  195.4  47.7  52.9]
 [  1.   67.8  36.6 114. ]
 [  1.  281.4  39.6  55.8]
 [  1.   69.2  20.5  18.3]
 [  1.  147.3  23.9  19.1]
 [  1.  218.4  27.7  53.4]
 [  1.  237.4   5.1  23.5]
 [  1.   13.2  15.9  49.6]
 [  1.  228.3  16.9  26.2]
 [  1.   62.3  12.6  18.3]
 [  1.  262.9   3.5  19.5]
 [  1.  142.9  29.3  12.6]
 [  1.  240.1  16.7  22.9]
 [  1.  248.8  27.1  22.9]
 [  1.   70.6  16.   40.8]
 [  1.  292.9  28.3  43.2]
 [  1.  112.9  17.4  38.6]
 [  1.   97.2   1.5  30. ]
 [  1.  265.6  20.    0.3]
 [  1.   95.7   1.4   7.4]
 [  1.  290.7   4.1   8.5]
 [  1.  266.9  43.8   5

In [7]:
x_trans=np.transpose(x)
x_trans_dot_x=x_trans.dot(x)
temp1=np.linalg.inv(x_trans_dot_x)
temp2=x_trans.dot(y)

theta=temp1.dot(temp2)

b0=theta[0]
b1=theta[1]
b2=theta[2]
b3=theta[3]

print("\nbeta0: ",b0)
print("\nbeta1: ",b1)
print("\nbeta2: ",b2)
print("\nbeta3: ",b3)


beta0:  2.9388893694594387

beta1:  0.0457646454553974

beta2:  0.1885300169182036

beta3:  -0.0010374930424761342


In [8]:
y_pred=b0+x1*b1+x2*b2+x3*b3
y_bar=np.mean(y)
ssr=np.sum((y-y_pred)*(y-y_pred))
sst=np.sum((y-y_bar)*(y-y_bar))
acc=1-(ssr/sst)
print("Accuracy Score: ", acc)

var=np.mean(y-y_pred)
MSE=var*var
print("Mean Squared Error: ", MSE)
print("Root Mean Squared Error: ", np.sqrt(MSE))

Accuracy Score:  0.8972106381789522
Mean Squared Error:  2.7144900963881323e-28
Root Mean Squared Error:  1.6475709685437324e-14
