# Create/Define single dimension / multi-dimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix.

In [4]:
import numpy as np
m=np.array([1,2,3])
print("Matrix 1: ", m)

n=np.array([[4,5,6],[1,3,7]])
print("Matrix 2:\n", n,'\n')

b=np.ones((2,3)).astype('int32')
print("Ones Matrix:\n", b,'\n')

a=np.zeros((2,2)).astype('int32')
print("Zeroes Matrix:\n", a,'\n')

c=np.random.randint(1,7,size=(3,3))
print("Random Value Matrix:\n", c,'\n')

d=np.diag([1,2,3,4])
print("Diagonal Matrix:\n",d)

Matrix 1:  [1 2 3]
Matrix 2:
 [[4 5 6]
 [1 3 7]] 

Ones Matrix:
 [[1 1 1]
 [1 1 1]] 

Zeroes Matrix:
 [[0 0]
 [0 0]] 

Random Value Matrix:
 [[5 3 2]
 [2 3 4]
 [5 4 3]] 

Diagonal Matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
