# Use command to compute the size of a matrix, size/length of a particular row/column, load data from a text file, store matrix data to a text file, finding out variables and their features in the current scope.

In [5]:
import numpy as np

x=np.array([[1,2,3,4],[5,6,7,8]])
print("SHAPE: ", x.shape,'\n')
print("SIZE: ", x.size,'\n')
print("ITEM SIZE: ", x.itemsize,'\n')

file=np.random.randint(1,20,size=(3,3))
np.savetxt('data1.txt',file)
np.genfromtxt('data1.txt',delimiter=' ')
file=file.astype('int32')
print("MATRIX:\n", file)

SHAPE:  (2, 4) 

SIZE:  8 

ITEM SIZE:  4 

MATRIX:
 [[ 4 13 12]
 [ 1  1 12]
 [17  3  8]]
